nombre = input ("Ingrese su nombre: ")
apellido = input ("Ingrese su apellido :")
edad = input ("Ingrese su edad :")
print(f"Nombre: {nombre}" )
print(f"Apellido: {apellido}" )
print(f"Edad: {edad}" )